solr-precreate: look for _default (Solr 7) configset as well as data_driven_schema_configs

diff --git a/6.4/alpine/scripts/solr-precreate b/6.4/alpine/scripts/solr-precreate
--- a/6.4/alpine/scripts/solr-precreate
+++ b/6.4/alpine/scripts/solr-precreate
@@ -20,7 +20,22 @@ fi
 . /opt/docker-solr/scripts/run-initdb
 
 CORE=${1:-gettingstarted}
-CONFIG_SOURCE=${2:-'/opt/solr/server/solr/configsets/data_driven_schema_configs'}
+CONFIG_SOURCE="${2:-}"
+if [[ -z "$CONFIG_SOURCE" ]]; then
+    DEFAULT_CONFIGS=(_default data_driven_schema_configs)
+    for config_dir in "${DEFAULT_CONFIGS[@]}"; do
+        config_dir="/opt/solr/server/solr/configsets/$config_dir"
+        if [ -d "$config_dir" ]; then
+           CONFIG_SOURCE="$config_dir"
+           break
+        fi
+    done
+    if [[ -z $CONFIG_SOURCE ]]; then
+        echo "Cannot find default config"
+        exit 1
+    fi
+fi
+
 if [[ -z $SOLR_HOME ]]; then
     coresdir="/opt/solr/server/solr/mycores"
     mkdir -p $coresdir
